import React, { useState } from 'react';
import pptxgen from "pptxgenjs";
import { api } from '../../lib/api';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { FileText, Presentation, Loader2, Download } from 'lucide-react';

interface DocExportProps {
  meetingId: string;
}

export const DocExport: React.FC<DocExportProps> = ({ meetingId }) => {
  const [loading, setLoading] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [language, setLanguage] = useState<string>("English");

  const generateSlides = async () => {
    setLoading('slides');
    setError(null);
    try {
      const response = await api.post(`/api/meetings/${meetingId}/generate/slides`, { language });
      const data = response.data;

      // Create PPTX
      const pres = new pptxgen();
      pres.layout = 'LAYOUT_16x9';

      // Title Slide
      const slide1 = pres.addSlide();
      slide1.addText(data.title, { x: 1, y: 1, w: 8, h: 1, fontSize: 36, align: 'center', bold: true });
      slide1.addText(`Generated by AI Meeting Companion`, { x: 1, y: 3, w: 8, h: 0.5, fontSize: 18, align: 'center', color: '888888' });

      // Content Slides
      data.slides.forEach((slideData: any) => {
        const slide = pres.addSlide();

        // Header
        slide.addText(slideData.title, { x: 0.5, y: 0.5, w: 9, h: 0.8, fontSize: 24, bold: true, color: '363636' });

        // Bullets
        const bullets = slideData.bullets.map((b: string) => ({ text: b, options: { fontSize: 16, breakLine: true } }));
        slide.addText(bullets, { x: 0.5, y: 1.5, w: 9, h: 3.5, bullet: true });

        // Notes
        if (slideData.speakerNotes) {
          slide.addNotes(slideData.speakerNotes);
        }
      });

      pres.writeFile({ fileName: `Meeting-Slides-${language}-${new Date().toISOString().split('T')[0]}.pptx` });

    } catch (err) {
      console.error(err);
      setError("Failed to generate slides.");
    } finally {
      setLoading(null);
    }
  };

  const generateDoc = async (type: string, label: string) => {
    setLoading(type);
    setError(null);
    try {
      const response = await api.post(`/api/meetings/${meetingId}/generate/${type}`, { language });
      const content = response.data.content;

      // Download as file
      const blob = new Blob([content], { type: 'text/markdown' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${label.replace(/ /g, '-')}-${language}-${new Date().toISOString().split('T')[0]}.md`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);

    } catch (err) {
      console.error(err);
      setError(`Failed to generate ${label}.`);
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-500">

      <div className="flex items-center justify-end gap-2">
        <span className="text-sm font-medium text-muted-foreground">Output Language:</span>
        <div className="flex bg-muted rounded-md p-1">
          <button
            onClick={() => setLanguage("English")}
            className={`px-3 py-1 text-sm rounded-sm transition-colors ${language === "English" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"}`}
          >
            English
          </button>
          <button
            onClick={() => setLanguage("Amharic")}
            className={`px-3 py-1 text-sm rounded-sm transition-colors ${language === "Amharic" ? "bg-background shadow-sm text-foreground" : "text-muted-foreground hover:text-foreground"}`}
          >
            Amharic
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

        {/* Presentation Card */}
        <Card className="hover:bg-accent/5 transition-colors">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Presentation className="h-5 w-5 text-purple-600" />
              PowerPoint Presentation
            </CardTitle>
            <CardDescription>
              Auto-generate slides with agenda, key points, and next steps.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button
              onClick={generateSlides}
              disabled={!!loading}
              className="w-full bg-purple-600 hover:bg-purple-700 text-white"
            >
              {loading === 'slides' ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
              Generate .pptx ({language})
            </Button>
          </CardContent>
        </Card>

        {/* Documents Card */}
        <Card className="hover:bg-accent/5 transition-colors">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-blue-600" />
              Project Documents
            </CardTitle>
            <CardDescription>
              Generate structured documents from meeting context.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid grid-cols-2 gap-2">
            <Button variant="outline" onClick={() => generateDoc('proposal', 'Project Proposal')} disabled={!!loading}>
              {loading === 'proposal' ? <Loader2 className="h-4 w-4 animate-spin" /> : "Proposal"}
            </Button>
            <Button variant="outline" onClick={() => generateDoc('user_stories', 'User Stories')} disabled={!!loading}>
              {loading === 'user_stories' ? <Loader2 className="h-4 w-4 animate-spin" /> : "User Stories"}
            </Button>
            <Button variant="outline" onClick={() => generateDoc('technical_spec', 'Tech Spec')} disabled={!!loading}>
              {loading === 'technical_spec' ? <Loader2 className="h-4 w-4 animate-spin" /> : "Tech Spec"}
            </Button>
            <Button variant="outline" onClick={() => generateDoc('marketing', 'Marketing Copy')} disabled={!!loading}>
              {loading === 'marketing' ? <Loader2 className="h-4 w-4 animate-spin" /> : "Marketing"}
            </Button>
          </CardContent>
        </Card>
      </div>

      {error && (
        <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/20 text-red-400 text-center text-sm">
          {error}
        </div>
      )}
    </div>
  );
};

// Refactor pass 17: verified component render.
